/**
 * Text in an Activity Projection.
 *
 * Fixed chrome is projected as a stable message id plus parameters, never as finished copy: the UI
 * locale registry owns the wording and renders it in the current `uiLocale`. Content keeps the
 * language it was written in, so a Goal's research question, an Agent's own summary and an upstream
 * error text travel as plain text.
 */
export type ActivityMessageKey =
	// Reused product chrome already registered for the Activity panel.
	| "goalActivity.stateSucceeded"
	| "goalActivity.stateRunning"
	| "goalActivity.statusQueued"
	| "goalActivity.stateFailed"
	| "goalActivity.statusCancelled"
	| "goalActivity.providerRecovered"
	| "goalActivity.providerFallback.running"
	| "goalActivity.providerFallback.succeeded"
	| "goalActivity.providerFallback.uncovered"
	// Usage and shared counters.
	| "activityChrome.usage.modelCalls"
	| "activityChrome.usage.toolCalls"
	| "activityChrome.usage.cost"
	| "activityChrome.status.interrupted"
	// Activity Steps the Runtime records for one Run.
	| "activityChrome.step.parallel"
	| "activityChrome.stage.inputResolution"
	| "activityChrome.stage.pipelineStart"
	| "activityChrome.stage.pipelineFinish"
	| "activityChrome.stage.runtimeGate"
	| "activityChrome.stage.workspaceRun"
	| "activityChrome.stage.primeSearch"
	| "activityChrome.stage.primeSearchBatch"
	| "activityChrome.stage.cornellNote"
	| "activityChrome.stage.cornellNoteGeneric"
	| "activityChrome.stage.reportWriter"
	| "activityChrome.stage.internal"
	// Agent Activities.
	| "activityChrome.agent.running"
	| "activityChrome.agent.willRerun"
	| "activityChrome.agent.endedWithRun"
	| "activityChrome.agent.runningPlain"
	| "activityChrome.agent.interruptedHere"
	| "activityChrome.agent.noCompletionRecord"
	| "activityChrome.agent.usingTool"
	| "activityChrome.agent.finishedTool"
	// Research Runs.
	| "activityChrome.research.initialized"
	| "activityChrome.research.searching"
	| "activityChrome.research.evidence"
	| "activityChrome.research.planAuthoring"
	| "activityChrome.research.planSelected"
	| "activityChrome.research.chaptersWriting"
	| "activityChrome.research.citationCompiling"
	| "activityChrome.research.markdownGating"
	| "activityChrome.research.interrupted"
	| "activityChrome.research.published"
	| "activityChrome.research.skipped"
	| "activityChrome.research.failed"
	| "activityChrome.research.cancelled"
	| "activityChrome.research.failedSeeDetail"
	| "activityChrome.research.skippedNoIncrement"
	| "activityChrome.research.skippedNoEvidence"
	| "activityChrome.research.sourceNoteFailures"
	| "activityChrome.research.degradedFetch"
	| "activityChrome.research.providerReplaced"
	| "activityChrome.research.providerUncovered"
	| "activityChrome.research.resume"
	| "activityChrome.research.resumeUnsupported"
	| "activityChrome.research.checkpointFromAgent"
	| "activityChrome.research.checkpointFromStage"
	| "activityChrome.research.checkpointWithoutManifest"
	| "activityChrome.research.backendStopped"
	| "activityChrome.research.openReport"
	| "activityChrome.research.scheduleTitle"
	| "activityChrome.research.scheduleSources"
	| "activityChrome.research.scheduleNotes"
	// A model Provider's HTTP error, read by `shared/provider-error.ts`; chat renders the same copy.
	| "activityChrome.providerError.withMessage"
	| "activityChrome.providerError.statusOnly"
	// Provider access inside a Research Run.
	| "activityChrome.provider.coolingTitle"
	| "activityChrome.provider.coolingSummary"
	| "activityChrome.provider.recoveredTitle"
	| "activityChrome.provider.unavailableTitle"
	| "activityChrome.provider.unavailableSummary"
	| "activityChrome.provider.fallbackTitle"
	// Wiki updates.
	| "activityChrome.wiki.updateTitle"
	| "activityChrome.wiki.batchTitle"
	| "activityChrome.wiki.batchRunning"
	| "activityChrome.wiki.batchInterrupted"
	| "activityChrome.wiki.batchFailed"
	| "activityChrome.wiki.batchCancelled"
	| "activityChrome.wiki.pageCount"
	| "activityChrome.wiki.reusedCheckpoint"
	| "activityChrome.wiki.maintainerRunning"
	| "activityChrome.wiki.maintainerInterrupted"
	| "activityChrome.wiki.maintainerFailed"
	| "activityChrome.wiki.maintainerCancelled"
	| "activityChrome.wiki.curatorTitle"
	| "activityChrome.wiki.curatorTitleIndexed"
	| "activityChrome.wiki.curatorRunning"
	| "activityChrome.wiki.curatorInterrupted"
	| "activityChrome.wiki.curatorFailed"
	| "activityChrome.wiki.publishTitle"
	| "activityChrome.wiki.publishRunning"
	| "activityChrome.wiki.publishInterrupted"
	| "activityChrome.wiki.publishFailed"
	| "activityChrome.wiki.interruptedReason"
	| "activityChrome.wiki.batchCheckpoint"
	| "activityChrome.wiki.resume"
	| "activityChrome.wiki.resumeLimit"
	| "activityChrome.wiki.batches"
	| "activityChrome.wiki.open"
	| "activityChrome.wiki.queued"
	| "activityChrome.wiki.interruptedSummary"
	| "activityChrome.wiki.failedCurator"
	| "activityChrome.wiki.failedPublication"
	| "activityChrome.wiki.failedGeneric"
	| "activityChrome.wiki.cancelled"
	| "activityChrome.wiki.partialSummary"
	| "activityChrome.wiki.partialBatches"
	| "activityChrome.wiki.partialSources"
	| "activityChrome.wiki.noChange"
	| "activityChrome.wiki.updated"
	| "activityChrome.wiki.creating"
	| "activityChrome.wiki.batchProgress"
	// Topic Plan confirmation.
	| "activityChrome.topicPlan.generatingTitle"
	| "activityChrome.topicPlan.generatingSummary"
	| "activityChrome.topicPlan.generationFailedTitle"
	| "activityChrome.topicPlan.generationFailedSummary"
	| "activityChrome.topicPlan.draftTitle"
	| "activityChrome.topicPlan.confirmTitle"
	| "activityChrome.topicPlan.awaitingConfirmation"
	| "activityChrome.topicPlan.confirmed"
	| "activityChrome.topicPlan.confirmedWikiFailed"
	| "activityChrome.topicPlan.confirmedWikiUpdated"
	| "activityChrome.topicPlan.confirmedWikiRunning"
	| "activityChrome.topicPlan.reviewReason"
	| "activityChrome.topicPlan.awaitingAttention"
	| "activityChrome.topicPlan.reframeFailedAttention"
	| "activityChrome.topicPlan.review"
	| "activityChrome.topicPlan.retryReframe"
	| "activityChrome.topicPlan.draftStep"
	| "activityChrome.topicPlan.draftStepSummary"
	| "activityChrome.topicPlan.confirmStep"
	| "activityChrome.topicPlan.confirmWaiting"
	| "activityChrome.topicPlan.confirmSuperseded"
	| "activityChrome.topicPlan.confirmActivated"
	| "activityChrome.topicPlan.reframeStep"
	| "activityChrome.topicPlan.reframeNoWiki"
	| "activityChrome.topicPlan.reframeFailedStep"
	| "activityChrome.topicPlan.reframeRunning"
	// Podcast generation.
	| "activityChrome.podcast.title"
	| "activityChrome.podcast.step"
	| "activityChrome.podcast.open"
	| "activityChrome.podcast.retry"
	| "activityChrome.podcast.queued"
	| "activityChrome.podcast.running"
	| "activityChrome.podcast.done"
	| "activityChrome.podcast.skipped"
	| "activityChrome.podcast.failed"
	// Frontend Activity Step groups.
	| "goals.activityStepGroups.executionPhase"
	| "goals.activityStepGroups.shardOrganization"
	| "goals.activityStepGroups.cornellNotes"
	| "goals.activityStepGroups.wikiWorkers"
	| "goals.activityStepGroups.wikiCurator"
	| "goals.activityStepGroups.publication"
	| "goalActivity.currentExecution"
	| "goalActivity.previousExecution";

/** One part of an Activity Text: fixed chrome by message id, or content in its own language. */
export type ActivityMessage =
	| { key: ActivityMessageKey; params?: Record<string, string | number>; text?: undefined }
	| { text: string; key?: undefined };

/** Content as a plain string, or fixed chrome and content composed in projection order. */
export type ActivityText = string | ActivityMessage[];

export function chrome(
	key: ActivityMessageKey,
	params?: Record<string, string | number>,
): ActivityMessage[] {
	return [params ? { key, params } : { key }];
}
