import type { SourceDescriptor } from "../source-descriptors.js";

export const huggingface: SourceDescriptor = {
	id: "huggingface",
	auth: "api_key",
	verify: "source_service",
	fields: [{ id: "huggingface_token", env: "SOURCE_SERVICE_HUGGINGFACE_TOKEN", legacyEnv: ["HF_TOKEN"] }],
	provider: {
		id: "huggingface",
		runtime: { kind: "source_service", minIntervalMs: 750 },
		catalog: {
			implementationVersion: "huggingface-hub-http-v5",
			capability: "Hugging Face Hub papers, model card README files, exact model and dataset metadata, benchmark leaderboards, and repository discovery through native HTTP APIs",
			supportedContentTypes: ["application/json", "text/markdown", "application/pdf"],
			workerPython: { module: "tools.huggingface" },
			workerSkills: ["prime-huggingface-selection-skill"],
			fullTextAvailability: "mixed",
			credentialRequirement: "optional",
			reliabilityTier: 1,
			freshness: "realtime",
			costClass: "free",
			latencyClass: "low",
			capabilities: ["scholarly_papers", "model_repositories", "datasets", "spaces"],
			sourceClass: "specialized",
			queryContract: {
				input: "provider_syntax",
				schemaVersion: 1,
				instructions: [
					"Use tools.huggingface.model_tags(tag_type='pipeline_tag') to discover current Provider-native model tasks instead of guessing task names.",
					"Use tools.huggingface.papers_search(query=...) for keyword search and paper_info for known arXiv IDs.",
					"For papers, narrow with paper_profile(depth='metadata'), inspect only finalists with depth='front', then call download_paper only for retained candidates; its bundle contains paper.md and metadata.json with native project and GitHub links.",
					"Use tools.huggingface.list_daily_papers or paginate_daily_papers only for the Daily Papers feed; neither accepts query, and sort must be published_at or trending.",
					"Daily Papers date, week, and month select when papers appeared in that feed, not their original published_at values.",
					"For explicitly exhaustive Daily Papers coverage, paginate through the assignment's deterministic feed and time boundary to the terminal cursor. Otherwise stop under the assigned evidence rule.",
					"Use tools.huggingface.models or datasets for repository discovery. In a discovery program, exact repository IDs must come from that program's own discovery results before calling model_info or dataset_info; otherwise a fixed ID must come from an `[exact]` Planner input.",
					"Use tools.huggingface.model_card for the complete README.md of an exact model repository; read the returned download_path.",
					"Use tools.huggingface.dataset_leaderboard only for benchmark datasets with submitted evaluation results; each row is a reported score, not independent verification.",
					"Use tools.huggingface.spaces only when the assignment specifically asks for a hosted application or demo.",
					"For a bounded model date range, use tools.huggingface.models_created_between for each relevant pipeline_tag. Do not replace it with an arbitrary top-N page.",
					"Use base_model_relation='base' as a high-precision canonical lane, then inspect the unfiltered task lane for official capability-distinct derivatives.",
					"For explicitly exhaustive model or dataset discovery, loop tools.huggingface.models or datasets with the opaque huggingface_page.next_cursor to the terminal cursor. Otherwise paginate while assigned evidence remains uncovered.",
					"Do not treat a chosen total_results value as proof of complete discovery.",
					"The assigned Provider child discovers, shortlists, and acquires selected Hugging Face repository files or papers.",
				],
				examples: [
					'huggingface.papers_search("agent evaluation", max_results=20)',
					'huggingface.list_daily_papers(week="2026-W28", sort="trending", max_results=20)',
					'huggingface.models(search="retrieval", sort="trending_score", max_results=50)',
					'huggingface.datasets(filters=["language:zh"], sort="downloads", max_results=50)',
					'huggingface.model_info("openai/whisper-large-v3")',
					'huggingface.model_card("openai/whisper-large-v3")',
					'huggingface.dataset_leaderboard("SWE-bench/SWE-bench_Verified", max_results=10)',
				],
			},
			supportedFields: [
				"title", "url", "authors", "summary", "publication_date", "submitted_at", "upvotes", "downloads", "likes",
				"tags", "pipeline_tag", "library_name", "sdk", "sha", "card_data", "model_index", "document_url", "artifact_path", "pdf_url", "next_cursor",
				"front_excerpt", "headings", "markdown_path", "metadata_path",
				"dataset_id", "model_id", "tag_type", "tag_id", "tag_label", "rank", "score", "verified",
			],
			supportedFilters: [
				"date", "week", "month", "submitter", "search", "author", "filters", "apps", "gated",
				"inference", "inference_provider", "pipeline_tag", "trained_datasets", "num_parameters",
				"base_model_relation", "tag_type",
				"datasets", "models", "linked", "sort", "cursor", "page", "limit",
			],
			evidenceTypes: ["primary_document", "preprint_metadata", "model_card", "dataset_card", "space_card"],
			operations: [
				"papers_list", "papers_search", "papers_info", "papers_preview", "papers_download", "models_info", "models_card", "model_tags", "models_list", "datasets_info",
				"datasets_leaderboard", "datasets_list", "spaces_list",
				"paginated_acquisition", "document_download",
			],
		},
	},
};
