import assert from "node:assert/strict";
import i18n from "../../web/src/app/i18n.js";
import { formatBytes, formatClockDuration, formatDate, formatDuration, formatElapsedSeconds, formatRelativeTime } from "../../web/src/shared/lib/format.js";

await i18n.changeLanguage("en");
assert.equal(formatBytes(-1), "-");
assert.equal(formatBytes(NaN), "-");
assert.equal(formatBytes(0), "0 B");
assert.equal(formatBytes(1023), "1023 B");
assert.equal(formatBytes(1024), "1.0 KB");
assert.equal(formatBytes(1024 ** 2), "1.0 MB");
assert.equal(formatBytes(1024 ** 3), "1.00 GB");
assert.equal(formatClockDuration(undefined, { fallback: "" }), "");
assert.equal(formatClockDuration(0), "0:00");
assert.equal(formatClockDuration(59.6, { padMinutes: true }), "01:00");
assert.equal(formatClockDuration(3661), "61:01");
assert.equal(formatClockDuration(3661, { hours: true }), "1:01:01");
assert.equal(formatDuration(-1), "--");
assert.equal(formatDuration(1250), "1.3s");
assert.equal(formatDuration(61000), "1m 1s");
assert.equal(formatDuration(120000), "2m+");
assert.equal(formatElapsedSeconds(1250), "1.25 sec");
const now = Date.parse("2026-09-09T12:00:00Z");
assert.equal(formatRelativeTime(now + 1000, "en", now), "now");
assert.equal(formatRelativeTime(now - 60000, "en", now), "1 minute ago");
assert.equal(formatRelativeTime(now - 3600000, "en", now), "1 hour ago");
assert.equal(formatRelativeTime(now - 86400000, "en", now), "yesterday");
assert.equal(formatRelativeTime("invalid", "en", now), "");
assert.equal(formatDate("invalid"), "invalid");
assert.equal(formatDate("invalid", {}, "en", ""), "");
const dateOptions: Intl.DateTimeFormatOptions = { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" };
assert.equal(formatDate(now, dateOptions, "en"), "Sep 9, 2026");
assert.equal(formatDate(now, dateOptions, "zh-CN"), "2026年9月9日");
console.log("Shared formatting checks passed");
